version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: credit-scoring-backend

  frontend:
    build: ./frontend/credit-scoring-frontend
    ports:
      - "3000:3000"
    container_name: credit-scoring-frontend
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/credit-scoring-frontend/node_modules:/app/node_modules
